#!/bin/bash
clear
#INICIO AUTOMATICO
ps x | grep 'udpvpn7300' | grep -v 'grep' || screen -dmS udpvpn7300 /bin/udp.sh 7300 >/dev/null 2>&1
ps x | grep 'udpvpn7400' | grep -v 'grep' || screen -dmS udpvpn7400 /bin/udp.sh 7400 >/dev/null 2>&1
ps x | grep 'udpvpn7500' | grep -v 'grep' || screen -dmS udpvpn7500 /bin/udp.sh 7500 >/dev/null 2>&1
ps x | grep 'udpvpn7600' | grep -v 'grep' || screen -dmS udpvpn7600 /bin/udp.sh 7600 >/dev/null 2>&1
ps x | grep 'udpvpn7700' | grep -v 'grep' || screen -dmS udpvpn7700 /bin/udp.sh 7700 >/dev/null 2>&1
systemctl is-active --quiet proxy8080 || {  proxy8080-restart.sh; } >/dev/null 2>&1
systemctl is-active --quiet ch || {  ch-restart.sh; } >/dev/null 2>&1
netstat -tlpn | grep -w 8787 > /dev/null || {  screen -r -S 'flask' -X quit;  screen -dmS flask python3 /root/terminal/service.py; }
